This notebook is basic demonstartaion of the numpy function as vector operations

x=(x1,x2,...,xn)  is a row vector then  np.exp(x)np.exp(x)  will apply the exponential function to every element of x. The output will thus be:  np.exp(x)=(ex1,ex2,...,exn)np.exp(x)=(ex1,ex2,...,exn)

In [5]:
import numpy as np

# example of np.exp
x = np.array([1, 2, 3])
print(np.exp(x)) # result is (exp(1), exp(2), exp(3))

[  2.71828183   7.3890561   20.08553692]


In [6]:
# example of vector operation
x = np.array([1, 2, 3])
print (x + 3)

[4 5 6]


sigmoid function using numpy


In [7]:
def sigmoid(x):
    s = np.exp(x)/(1+np.exp(x))    
    return s

In [12]:
x = np.array([1, 2, 3])
s = sigmoid(x)
print(s)
sigmoid(x)

[ 0.73105858  0.88079708  0.95257413]


array([ 0.73105858,  0.88079708,  0.95257413])

Compute Sigmoid gradient

In [13]:
def sigmoid_derivative(x):
    s = sigmoid(x)
    ds = np.multiply(s, (1-s))    
    return ds

In [14]:
x = np.array([1, 2, 3])
print ("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)))
sigmoid_derivative(x)

sigmoid_derivative(x) = [ 0.19661193  0.10499359  0.04517666]


array([ 0.19661193,  0.10499359,  0.04517666])

In [16]:
def image2vector(image):
    v = image.reshape((image.shape[0]*image.shape[1]*image.shape[2], 1))    
    return v

In [17]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[ 0.67826139]
 [ 0.29380381]
 [ 0.90714982]
 [ 0.52835647]
 [ 0.4215251 ]
 [ 0.45017551]
 [ 0.92814219]
 [ 0.96677647]
 [ 0.85304703]
 [ 0.52351845]
 [ 0.19981397]
 [ 0.27417313]
 [ 0.60659855]
 [ 0.00533165]
 [ 0.10820313]
 [ 0.49978937]
 [ 0.34144279]
 [ 0.94630077]]


L1 and L2 loss functions implementation below

In [18]:
def L1(yhat, y):
    loss = np.sum(abs(np.subtract(yhat,y)))    
    return loss

In [19]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


In [20]:
def L2(yhat, y):
    loss =  np.dot((yhat-y),(yhat-y))
    return loss